<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion><groupId>io.github.xmori</groupId><artifactId>package-aggregator</artifactId><version>1.1.0</version><packaging>pom</packaging>
  <modules>
    <module>packages/maven/initials-from-name</module>
    <module>packages/maven/mask-string</module>
    <module>packages/maven/human-file-size</module>
    <module>packages/maven/human-duration</module>
    <module>packages/maven/relative-time-lite</module>
    <module>packages/maven/date-range</module>
    <module>packages/maven/business-days</module>
    <module>packages/maven/age-from-date</module>
    <module>packages/maven/random-id-lite</module>
    <module>packages/maven/secure-pin</module>
    <module>packages/maven/otp-generator-lite</module>
    <module>packages/maven/random-string-secure</module>
    <module>packages/maven/password-strength-lite</module>
    <module>packages/maven/email-normalizer</module>
    <module>packages/maven/url-normalizer-lite</module>
    <module>packages/maven/strip-tracking-params</module>
    <module>packages/maven/query-string-object</module>
    <module>packages/maven/join-url</module>
  </modules>
</project>
